# Generated by Django 2.2.5 on 2019-09-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField(max_length=300, unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('credit', models.URLField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
