# Generated by Django 2.2.5 on 2019-09-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batfact',
            name='type',
            field=models.CharField(choices=[('FL', 'FLIGHT'), ('SL', 'SLEEP'), ('SP', 'SPECIES'), ('CO', 'COMMUNITY'), ('OT', 'OTHER')], default='OT', max_length=2),
        ),
    ]
