# Generated by Django 2.2.5 on 2019-09-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0002_batfact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batfact',
            name='type',
            field=models.CharField(choices=[('FL', 'Flight'), ('SL', 'Sleep'), ('SP', 'Species'), ('CO', 'Community'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
