# Generated by Django 2.2.5 on 2019-09-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0003_auto_20190923_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='batfact',
            name='title',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
