# Generated by Django 2.2.5 on 2019-09-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0004_batfact_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField()),
                ('img', models.ImageField(upload_to='charities/')),
            ],
        ),
    ]
