# Generated by Django 2.2.5 on 2019-09-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0005_charity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charity',
        ),
    ]
