# Generated by Django 2.2.5 on 2019-10-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0006_delete_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batfact',
            name='fact',
            field=models.TextField(max_length=750, unique=True),
        ),
        migrations.AlterField(
            model_name='batfact',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
