# Generated by Django 2.2.5 on 2019-09-28 18:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0006_delete_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batfact',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='img'),
        ),
    ]
