# Generated by Django 2.2.5 on 2019-09-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0007_auto_20190928_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batfact',
            name='fact',
            field=models.TextField(max_length=750, unique=True),
        ),
    ]
